name: h2spec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  conformance:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    strategy:
      matrix:
        ruby-version: ['4.0']
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Ruby
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          gem --version
          gem install bundler
          bundle --version
          bundle install
      - name: Install h2spec
        run: |
          set -eu
          curl -Ls https://github.com/summerwind/h2spec/releases/download/v2.6.0/h2spec_linux_amd64.tar.gz | tar xz
          mkdir -p $GITHUB_WORKSPACE/bin
          mv h2spec $GITHUB_WORKSPACE/bin/h2spec
          chmod +x $GITHUB_WORKSPACE/bin/h2spec
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
      - name: Run conformance test
        run: bundle exec rake conformance
      - uses: mikepenz/action-junit-report@a9170d5795813c01ab4901ffb045b52bab4ab09d # v6.5.0
        if: success()
        with:
          report_paths: conformance/reports/h2spec.xml
          detailed_summary: true
